FROM ubuntu:22.04

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]
RUN apt-get update                                    &&\
  apt-get install -y --no-install-recommends            \
  git wget ca-certificates                              \
  clang-format-14 clang-14 clang-tidy-14 lld-14         \
  build-essential meson gcc-12 g++-12 cmake             \
  google-perftools                                      \
  libaio-dev                                            \
  libboost-all-dev                                      \
  libdouble-conversion-dev                              \
  libdwarf-dev                                          \
  libgflags-dev                                         \
  libgmock-dev                                          \
  libgoogle-glog-dev                                    \
  libgoogle-perftools-dev                               \
  libgtest-dev                                          \
  liblz4-dev                                            \
  liblzma-dev                                           \
  libssl-dev                                            \
  libunwind-dev                                         \
  libuv1-dev                                          &&\
  apt-get clean                                       &&\
  rm -rf /var/lib/apt/lists/*                  
  
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ARG TARGETARCH=amd64
ARG FDB_VERSION=7.3.63
ARG FDB_ARCH_SUFFIX=amd64
ARG FDB_CLIENT_URL="https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-clients_${FDB_VERSION}-1_${FDB_ARCH_SUFFIX}.deb"
ARG FDB_SERVER_URL="https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/foundationdb-server_${FDB_VERSION}-1_${FDB_ARCH_SUFFIX}.deb"

RUN curl -o fdb-cli.deb -L "${FDB_CLIENT_URL}" && \
# curl -o fdb-srv.deb -L "${FDB_SERVER_URL}" && \
dpkg -i fdb-cli.deb && \
# dpkg -i fdb-srv.deb && \
rm fdb-cli.deb
# fdb-srv.deb 

ARG LIBFUSE_VERSION=3.16.2
ARG LIBFUSE_DOWNLOAD_URL="https://github.com/libfuse/libfuse/releases/download/fuse-${LIBFUSE_VERSION}/fuse-${LIBFUSE_VERSION}.tar.gz"
RUN wget -O- ${LIBFUSE_DOWNLOAD_URL}        |\
  tar -xzvf - -C /tmp                      &&\
  cd /tmp/fuse-${LIBFUSE_VERSION}          &&\
  mkdir build && cd build                  &&\
  meson setup .. && meson configure -D default_library=both &&\
  ninja && ninja install &&\
  rm -f -r /tmp/fuse-${LIBFUSE_VERSION}*
  


COPY docker_build_exec_script.sh /opt/commands.sh
WORKDIR /opt